### ISSUE TITLE
Fatal error: Call to undefined function GuzzleHttp\choose_handler() in GuzzleHttp/HandlerStack.php on line 40

### ISSUE THREAD

**Issue by Nik-ADA** [grnhse/greenhouse-tools-php#2]
Hi
i give above error on using latest version of GuzzleHttp

**Comment by tdphillipsjr** [comment]
Hi,

This appears to be a Guzzle error.  Are you using Composer to manage this or trying to update these packages manually?

**Comment by Nik-ADA** [comment]
packages manually.

**Comment by tdphillipsjr** [comment]
I don't really know how the packages are going to interact without the use of Composer.  You are probably getting a conflict somewhere due to something not being autoloaded correctly.  Our suggestion here is to use [Composer](https://getcomposer.org/).  It will save you a lot of time and will work better than manual package management.

**Comment by standus** [comment]
Include basic files:
```
include_once dirname(dirname(__DIR__)).'/GuzzleHttp/functions.php';
include_once dirname(dirname(__DIR__)).'/GuzzleHttp/Psr7/functions.php';
include_once dirname(dirname(__DIR__)).'/GuzzleHttp/Promise/functions.php';
```
